### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by Fredo70** [StephenChou1017/react-big-scheduler#182]
Is this project dead? It would be a pity. Because it looks good. But I'm having trouble getting it to work. Also because of DnD. Many things are deprecated.

If it is no longer maintained, I will simply look for something else.

**Comment by aliehsan90** [comment]
Hey @Fredo70, I am currently using this project. What kind of issue are you facing?

**Comment by Fredo70** [comment]
I gave up and unfortunatly I don't write down the errors. But I got problems because of DnD. This project uses an old version. I was not able to get it working, whether with the old nor with the newest version. I don't need drag and drop. But it is mandatory to use it.
Anyway for now I give up. I will check back later if I need this component after all.

**Comment by aliehsan90** [comment]
Sure @Fredo70.

**Comment by beysong** [comment]
With `npm ls react-dnd` in the terminal check you library, you can see all the react-dnd versions in your npm package. it must be the version conflict of react-dnd.
Try to delete the other package Contained react-dnd and try again, good luck guys.

**Comment by HsnImam** [comment]
I am facing similar issue with 'react-dnd' context issue, the project relies on the old version and in my project we are already using newer version. I don't know how to resolve the `Could not find the drag and drop manager in the context of ResourceEvents.` issue.

**Comment by CamdenShaw** [comment]
I was having the same issues. [If you follow the examples](https://stephenchou1017.github.io/scheduler/#/) not the readme, you will see that you need to add this to your code:
<pre>
import { DragDropContext } from 'react-dnd'
import HTML5Backend from 'react-dnd-html5-backend'
class BigScheduler extends React.Component {
    ...
}
export default DragDropContext(HTML5Backend)(BigScheduler)
</pre>

**Comment by nnmer** [comment]
the way to run :
```
import {DndProvider} from 'react-dnd'
import HTML5Backend from 'react-dnd-html5-backend'
...
<DndProvider backend={HTML5Backend}>
  <Scheduler schedulerData={schedulerData}
    prevClick={()=>{}}
    nextClick={()=>{}}
    onSelectDate={()=>{}}
    onViewChange={()=>{}}
   />
</DndProvider>

```

**Comment by IleanaAldama** [comment]
Hey @nnmer can I cask which version of `react-dnd` and `react-big-shceduler` are you using?

**Comment by ajayjayendran** [comment]
@ChrisAldama have you got the issue fixed ? Could not find the drag and drop manager in the context of ResourceEvents.

**Comment by nnmer** [comment]
@ChrisAldama  That was the latest versions. I just did **npm i react-dnd react-dnd-html5-backend react-big-shceduler** . I've decided to go with another component, cannot get the version numbers for you now

**Comment by kermopajula** [comment]
@nnmer Since the project is dead here - may I ask, what did you go with?

**Comment by nnmer** [comment]
@kermopajula  I've went with https://github.com/namespace-ee/react-calendar-timeline

**Comment by usahai** [comment]
@nnmer Hey, I found that react-calendar-timeline is quite laggy. The lack of horizontal scrolling plus the dynamic re-rendering means that the end result doesn't appear very smooth. My guess is that it is re-rendering the details first, then the headers, which is why the headers are slower. Did you experience this problem?

**Comment by nnmer** [comment]
@usahai  I don't have much elements on the timeline, sometimes it does have some laggs, but in my use case it is not critical.
The horizontal scroll I've solved by dragging the timeline to left or right, again in my case it is enough as I just need to focus on a current month events

**Comment by qtnemo** [comment]
> 
> 
> the way to run :
> 
> ```
> import {DndProvider} from 'react-dnd'
> import HTML5Backend from 'react-dnd-html5-backend'
> ...
> <DndProvider backend={HTML5Backend}>
>   <Scheduler schedulerData={schedulerData}
>     prevClick={()=>{}}
>     nextClick={()=>{}}
>     onSelectDate={()=>{}}
>     onViewChange={()=>{}}
>    />
> </DndProvider>
> ```

I did just that but still get "Could not find the drag and drop manager in the context of ResourceEvents".  Tried everything I could find online but either didn't work or the imported elements were no longer in the current version of react-dnd.  Looked at react-calendar-timeline, but it didn't look as good as this component.
